# calculator



print (r" /------------------------------\ ")
print (" |                              |")
print (" |_____     CALCULATOR     _____| ")
print (" \_____\__________________/_____/ ")
print(     ) 
print(     )
a = input ("Enter first number : ")
b = input ("Enter second number : ")
print ()
print ()
input(" + ")
print ("The value of addition [+] is = [" ,int(a)  + int(b),"]")
print ()
print ("The value of substraction is [-] = [" ,int(a)  - int(b),"]")
print ()
print ("The value of multiplication is [*] = [" ,int(a)  * int(b),"]")
print ()
print ("The value of division is [/] = [" ,int(a)  / int(b),"]")
print ()
print ("The value of exponential is [**] = [" ,int(a)  ** int(b),"]")
print ()
print ("The value of floor is [//] = [" ,int(a)  // int(b),"]")
print ()
print ("The value of percentage [%] is = [" ,int(a)  % int(b),"% ]")
input ( )